# This is a basic workflow to help you get started with Actions

name: latex cookbook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  latex-job:
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v1
      - name: build pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cookbook.tex
      - name: stash pdf
        run: |
          mv cookbook.pdf $HOME
      - name: commit pdf
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github action"
          mv $HOME/cookbook.pdf $(pwd)
          git add cookbook.pdf
          git commit -m "Update pdf to reflect changes in .tex"
      - name: push pdf
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: false
#          github_token: {{ secrets.GITHUB_TOKEN }}
